-- =========================================
-- SQL ANALYSIS QUERIES
-- Retail Store Sales Analysis Project
-- =========================================


-- 1. TOTAL SALES
SELECT 
SUM(quantity * list_price) AS Total_Sales
FROM order_items;


-- 2. TOTAL ORDERS
SELECT 
COUNT(order_id) AS Total_Orders
FROM orders;


-- 3. TOTAL CUSTOMERS
SELECT 
COUNT(customer_id) AS Total_Customers
FROM customers;


-- 4. TOP 10 SELLING PRODUCTS
SELECT TOP 10
p.product_name,
SUM(oi.quantity) AS Total_Quantity_Sold
FROM order_items oi
JOIN products p
ON oi.product_id = p.product_id
GROUP BY p.product_name
ORDER BY Total_Quantity_Sold DESC;


-- 5. TOP 10 CUSTOMERS
SELECT TOP 10
c.first_name,
c.last_name,
SUM(oi.quantity * oi.list_price) AS Total_Spent
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
JOIN order_items oi
ON o.order_id = oi.order_id
GROUP BY c.first_name, c.last_name
ORDER BY Total_Spent DESC;


-- 6. STORE-WISE SALES
SELECT
s.store_name,
SUM(oi.quantity * oi.list_price) AS Store_Sales
FROM stores s
JOIN orders o
ON s.store_id = o.store_id
JOIN order_items oi
ON o.order_id = oi.order_id
GROUP BY s.store_name
ORDER BY Store_Sales DESC;


-- 7. MONTHLY SALES TREND
SELECT
MONTH(order_date) AS Month_Number,
SUM(oi.quantity * oi.list_price) AS Monthly_Sales
FROM orders o
JOIN order_items oi
ON o.order_id = oi.order_id
GROUP BY MONTH(order_date)
ORDER BY Month_Number;


-- 8. BRAND-WISE SALES
SELECT
b.brand_name,
SUM(oi.quantity * oi.list_price) AS Brand_Sales
FROM brands b
JOIN products p
ON b.brand_id = p.brand_id
JOIN order_items oi
ON p.product_id = oi.product_id
GROUP BY b.brand_name
ORDER BY Brand_Sales DESC;


-- 9. INVENTORY ANALYSIS
SELECT
p.product_name,
SUM(s.quantity) AS Stock_Available
FROM stocks s
JOIN products p
ON s.product_id = p.product_id
GROUP BY p.product_name
ORDER BY Stock_Available DESC;

-- =========================================
-- 10. TOP 10 PRODUCTS BY REVENUE
-- =========================================

SELECT TOP 10
p.product_name,
SUM(oi.quantity * oi.list_price) AS Product_Revenue
FROM order_items oi
JOIN products p
ON oi.product_id = p.product_id
GROUP BY p.product_name
ORDER BY Product_Revenue DESC;


-- =========================================
-- 11. CATEGORY-WISE SALES ANALYSIS
-- =========================================

SELECT
c.category_name,
SUM(oi.quantity * oi.list_price) AS Category_Sales
FROM categories c
JOIN products p
ON c.category_id = p.category_id
JOIN order_items oi
ON p.product_id = oi.product_id
GROUP BY c.category_name
ORDER BY Category_Sales DESC;


-- =========================================
-- 12. TOP 10 STORED PRODUCTS BY STOCK
-- =========================================

SELECT TOP 10
p.product_name,
SUM(s.quantity) AS Total_Stock
FROM stocks s
JOIN products p
ON s.product_id = p.product_id
GROUP BY p.product_name
ORDER BY Total_Stock DESC;
-- =========================================
-- 13. STAFF PERFORMANCE ANALYSIS
-- Revenue Generated by Each Staff Member
-- =========================================

SELECT
s.staff_id,
s.first_name,
s.last_name,
SUM(oi.quantity * oi.list_price) AS Revenue_Generated
FROM staffs s
JOIN orders o
ON s.staff_id = o.staff_id
JOIN order_items oi
ON o.order_id = oi.order_id
GROUP BY s.staff_id, s.first_name, s.last_name
ORDER BY Revenue_Generated DESC;
-- =========================================
-- 14. SHIPMENT DELAY ANALYSIS
-- On-Time vs Late Deliveries
-- =========================================

SELECT
order_id,
order_date,
required_date,
shipped_date,

CASE
    WHEN shipped_date <= required_date
    THEN 'On Time'

    WHEN shipped_date > required_date
    THEN 'Late Delivery'

    ELSE 'Pending Shipment'
END AS Shipment_Status

FROM orders;